---
title: "assignment"
output: html_document
date: "2026-02-20"
---

```{r setup, cache=TRUE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages({
  library(AnnotationHub) # to fetch genomes, annotations, etc.
  library(ensembldb)     # to manipulate ensembl gene annotations
  library(GenomicRanges) # data structure for genomic ranges 
  library(epiwraps)      # visualization
})
```

```{r}
ah<-AnnotationHub()
```


```{r}
# 1. Mouse EnsDb (v102, GRCm38)
query_mouse_ensdb <- query(ah, c("Mus musculus", "EnsDb", "102", "GRCm38"))
mouse_ensdb <- query_mouse_ensdb[[1]] # Downloads and loads the actual EnsDb object

# 2. Mouse genome sequence (dna_sm) in TwoBit format for GRCm38
query_mouse_dna <- query(ah, c("Mus musculus", "TwoBit", "GRCm38", "dna_sm"))
mouse_dna <- query_mouse_dna[[1]]

# 3. Drosophila melanogaster genome sequence (dna_sm) in TwoBit format for BDGP6
query_fly_dna <- query(ah, c("Drosophila melanogaster", "TwoBit", "BDGP6", "dna_sm"))
fly_dna <- query_fly_dna[[1]]
```
```{r}
# Extract all protein-coding genes
pc_genes <- genes(mouse_ensdb, filter = ~ gene_biotype == "protein_coding")

# 1. How many different Ensembl gene IDs?
num_gene_ids <- length(unique(pc_genes$gene_id))

# 2. How many different gene symbols?
num_gene_symbols <- length(unique(pc_genes$symbol))


cat("Number of unique Ensembl gene IDs:", num_gene_ids, "\n")
cat("Number of unique gene symbols:", num_gene_symbols, "\n")
```
```{r}
# 1. Extract exons, but only for protein-coding transcripts.
pc_exons <- exons(mouse_ensdb, 
                  filter = ~ tx_biotype == "protein_coding", 
                  columns = c("tx_id"))

# 2. Split the exons by their transcript ID
exons_by_tx <- split(pc_exons, pc_exons$tx_id)

# 3. Sum the width of the exons for each transcript

spliced_tx_lengths <- sum(width(exons_by_tx))

# 4. Plot the distribution
hist(log10(spliced_tx_lengths), 
     breaks = 50, 
     main = "Distribution of Protein-Coding Transcript Lengths (Mouse)",
     xlab = "Log10(Transcript Length in base pairs)",
     col = "steelblue", 
     border = "white")
```


